# Application configuration
spring.application.name=api-scheduler
server.port=8080

# MongoDB configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=scheduler
spring.mongodb.embedded.version=6.0.6

# Enable embedded MongoDB
spring.mongodb.embedded.enabled=true

# MongoDB persistence configuration
spring.mongodb.embedded.storage.database-dir=./data/mongodb
spring.mongodb.embedded.storage.repl-set-name=rs0

# Logging configuration
logging.level.org.springframework.data.mongodb=INFO
logging.level.com.scheduler.api=DEBUG
